name: eight_club
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  record: ^6.1.2
  video_player: ^2.10.0
  path_provider: ^2.1.5
  audio_waveforms: ^1.3.0
  just_audio: ^0.9.36
  permission_handler: ^11.0.1
  path: ^1.8.3
  camera: ^0.10.5+5
  video_thumbnail: ^0.5.3
  flutter_keyboard_visibility: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/onboarding_background.png

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Light.ttf
          weight: 200
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGrotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600